git clone https://github.com/TULiberalArts/Spanish.git
git clone https://github.com/TULiberalArts/German.git
git clone https://github.com/TULiberalArts/English.git
git clone https://github.com/TULiberalArts/American-Studies.git
git clone https://github.com/TULiberalArts/Anthropology.git
git clone https://github.com/TULiberalArts/Economics.git
git clone https://github.com/TULiberalArts/Environmental-Studies.git
git clone https://github.com/TULiberalArts/French.git
git clone https://github.com/TULiberalArts/Philosophy.git
git clone https://github.com/TULiberalArts/Global-Studies.git
git clone https://github.com/TULiberalArts/Sociology.git
git clone https://github.com/TULiberalArts/Gender-Sexuality-and-Womens-Studies.git
git clone https://github.com/TULiberalArts/Public-Policy.git
git clone https://github.com/TULiberalArts/Psychology.git
git clone https://github.com/TULiberalArts/Russian.git
git clone https://github.com/TULiberalArts/Religion.git
git clone https://github.com/TULiberalArts/Portuguese.git
git clone https://github.com/TULiberalArts/Political-Science.git
git clone https://github.com/TULiberalArts/Liberal-Studies.git
git clone https://github.com/TULiberalArts/Latin-American-Studies.git
git clone https://github.com/TULiberalArts/Neuroscience.git
git clone https://github.com/TULiberalArts/Italian.git
git clone https://github.com/TULiberalArts/Jewish-Studies.git
git clone https://github.com/TULiberalArts/Japanese.git
git clone https://github.com/TULiberalArts/Intellectual-Heritage.git
git clone https://github.com/TULiberalArts/History.git
git clone https://github.com/TULiberalArts/Greek-and-Roman-Classics.git
git clone https://github.com/TULiberalArts/Chinese.git
git clone https://github.com/TULiberalArts/Criminal-Justice.git
git clone https://github.com/TULiberalArts/Asian-Studies.git
git clone https://github.com/TULiberalArts/Creative-Writing.git
git clone https://github.com/TULiberalArts/Arabic.git
git clone https://github.com/TULiberalArts/Africology-and-African-American-Studies.git
git clone https://github.com/TULiberalArts/Geographic-Information-Systems.git
git clone https://github.com/TULiberalArts/Geography-and-Urban-Studies.git
git clone https://github.com/TULiberalArts/TUTheme-Documentation.git
git clone https://github.com/TULiberalArts/TUTheme-Boilerplate.git
